// @ts-check
import { defineConfig, passthroughImageService } from "astro/config";
import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";
import starlightLinksValidator from "starlight-links-validator";
import starlightPageActions from "starlight-page-actions";
import starlightLlmsTxt from "@hey-api/starlight-llms-txt";
import {
  onceHubSidebar,
  scheduleOnceSidebar,
  developersSidebar,
  scheduleOnceDevelopersSidebar,
} from "./src/sidebarConfig.mjs";
import { readFileSync } from "fs";
import { join } from "path";
import openapiToMarkdown from "./src/integrations/openapi-markdown.ts";

import tailwindcss from "@tailwindcss/vite";

// Load per-page lastmod cache (generated by scripts/generate-sitemap-lastmod-cache.mjs)
/** @type {Record<string, string>} */
let sitemapCache = {};
try {
  sitemapCache = JSON.parse(
    readFileSync(join(process.cwd(), "sitemap-lastmod-cache.json"), "utf-8"),
  );
} catch {
  // Cache file may not exist during dev or initial builds — that's okay
}

// https://astro.build/config
export default defineConfig({
  site: "https://help.staticso2.com",
  redirects: {
    "/scheduleonce":
      "/scheduleonce/introduction-to-booking-pages/getting-started-with-booking-pages/",
    "/developers": "/developers/overview/introduction/",
    "/scheduleonce/developers":
      "/scheduleonce/developers/client-side-api/embedded-booking-calendar-events/",
    "/contact-management/how-oncehub-associates-activities-with-contact":
      "/contact-management/how-contacts-are-identified-in-oncehub/",
    "/scheduleonce/account-integrations/api/":
      "/scheduleonce/account-integrations/automation/api/",
    "/scheduleonce/account-integrations/api/custom-integrations-with-oncehub-api/":
      "/scheduleonce/account-integrations/automation/api/custom-integrations-with-oncehub-api/",
  },
  image: {
    service: passthroughImageService(),
  },
  integrations: [
    sitemap({
      serialize(item) {
        try {
          const url = new URL(item.url);
          const cachedDate = sitemapCache[url.pathname];
          if (cachedDate) {
            item.lastmod = cachedDate;
          }
        } catch {
          // Ignore malformed URLs
        }
        return item;
      },
    }),
    starlight({
      title: "Help",
      logo: {
        src: "./src/assets/logo.svg",
        alt: "OnceHub Logo",
      },
      components: {
        Hero: "./src/components/Hero.astro",
        Sidebar: "./src/components/Sidebar.astro",
        SocialIcons: "./src/components/SocialIcons.astro",
        PageTitle: "./src/components/PageTitle.astro",
        SiteTitle: "./src/components/SiteTitle.astro",
        Header: "./src/components/Header.astro",
        Footer: "./src/components/Footer.astro",
        ThemeSelect: "./src/components/ThemeSelect.astro",
        Search: "./src/components/Search.astro",
      },
      disable404Route: true,
      customCss: ["./src/styles/fonts.css", "./src/styles/global.css"],
      lastUpdated: true,
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/oncehub" },
      ],
      sidebar: [
        ...onceHubSidebar,
        ...scheduleOnceSidebar,
        ...developersSidebar,
        ...scheduleOnceDevelopersSidebar,
      ],
      head: [
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-400-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-600-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-700-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
      ],
      plugins: [
        starlightLinksValidator({
          failOnError: false,
        }),
        starlightPageActions({
          actions: {
            chatgpt: true,
            claude: true,
            markdown: true,
          },
          share: false,
        }),
        starlightLlmsTxt({
          projectName: "OnceHub Help Center",
        }),
      ],
    }),
    openapiToMarkdown(),
  ],

  vite: {
    plugins: [tailwindcss()],
    server: {
      allowedHosts: [".trycloudflare.com"],
    },
  },
});
