// @ts-check
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";
import starlightLinksValidator from "starlight-links-validator";
import starlightPageActions from "starlight-page-actions";
import starlightLlmsTxt from "@hey-api/starlight-llms-txt";
import {
  onceHubSidebar,
  scheduleOnceSidebar,
  developersSidebar,
  scheduleOnceDevelopersSidebar,
} from "./src/sidebarConfig.mjs";
import { readFileSync, copyFileSync, mkdirSync } from "fs";
import { join } from "path";
import openapiToMarkdown from "./src/integrations/openapi-markdown.ts";

import tailwindcss from "@tailwindcss/vite";

/**
 * Astro integration to sync the Scalar standalone bundle from node_modules
 * to public/scalar/standalone.js automatically on dev server start and build.
 * @returns {import("astro").AstroIntegration}
 */
function syncScalarBundle() {
  return {
    name: "sync-scalar-bundle",
    hooks: {
      "astro:config:setup": () => {
        try {
          const src = join(
            process.cwd(),
            "node_modules/@scalar/api-reference/dist/browser/standalone.js",
          );
          const dest = join(process.cwd(), "public/scalar/standalone.js");
          mkdirSync(join(process.cwd(), "public/scalar"), { recursive: true });
          copyFileSync(src, dest);
        } catch (e) {
          console.warn("[sync-scalar-bundle] Failed to copy bundle:", e);
        }
      },
    },
  };
}

// Load per-page lastmod cache (generated by scripts/generate-sitemap-lastmod-cache.mjs)
/** @type {Record<string, string>} */
let sitemapCache = {};
try {
  sitemapCache = JSON.parse(
    readFileSync(join(process.cwd(), "sitemap-lastmod-cache.json"), "utf-8"),
  );
} catch {
  // Cache file may not exist during dev or initial builds — that's okay
}

// Determine GTM container ID based on the target site URL
const SITE_URL = process.env.SITE_URL || "https://help.oncehub.com";
const GTM_ID =
  SITE_URL === "https://help.oncehub.com" ? "GTM-WJ6GSHH" : "GTM-PL2LFVW2";

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  redirects: {
    "/scheduleonce":
      "/scheduleonce/introduction-to-booking-pages/getting-started-with-booking-pages/",
    "/developers": "/developers/overview/introduction/",
    "/scheduleonce/developers":
      "/scheduleonce/developers/client-side-api/embedded-booking-calendar-events/",
    "/contact-management/how-oncehub-associates-activities-with-contact":
      "/contact-management/how-contacts-are-identified-in-oncehub/",
    "/scheduleonce/account-integrations/api/":
      "/scheduleonce/account-integrations/automation/api/",
    "/scheduleonce/account-integrations/api/custom-integrations-with-oncehub-api/":
      "/scheduleonce/account-integrations/automation/api/custom-integrations-with-oncehub-api/",
  },

  integrations: [
    syncScalarBundle(),
    sitemap({
      serialize(item) {
        try {
          const url = new URL(item.url);
          const cachedDate = sitemapCache[url.pathname];
          if (cachedDate) {
            item.lastmod = cachedDate;
          }
        } catch {
          // Ignore malformed URLs
        }
        return item;
      },
    }),
    starlight({
      title: "Help",
      favicon: "/favicon.ico",
      logo: {
        src: "./src/assets/logo.svg",
        alt: "OnceHub Logo",
      },
      components: {
        Hero: "./src/components/Hero.astro",
        Sidebar: "./src/components/Sidebar.astro",
        SocialIcons: "./src/components/SocialIcons.astro",
        PageTitle: "./src/components/PageTitle.astro",
        SiteTitle: "./src/components/SiteTitle.astro",
        Header: "./src/components/Header.astro",
        Footer: "./src/components/Footer.astro",
        ThemeSelect: "./src/components/ThemeSelect.astro",
        Search: "./src/components/Search.astro",
      },
      disable404Route: true,
      customCss: ["./src/styles/fonts.css", "./src/styles/global.css"],
      lastUpdated: true,
      social: [
        { icon: "github", label: "GitHub", href: "https://github.com/oncehub" },
      ],
      sidebar: [
        ...onceHubSidebar,
        ...scheduleOnceSidebar,
        ...developersSidebar,
        ...scheduleOnceDevelopersSidebar,
      ],
      head: [
        // Google Tag Manager
        {
          tag: "script",
          content: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','${GTM_ID}');`,
        },
        {
          tag: "noscript",
          content: `<iframe src="https://www.googletagmanager.com/ns.html?id=${GTM_ID}" height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
        },
        {
          tag: "link",
          attrs: {
            rel: "icon",
            href: "/favicon.ico",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-300-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-400-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-600-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "preload",
            href: "/fonts/open-sans-latin-700-normal.woff2",
            as: "font",
            type: "font/woff2",
            crossorigin: "anonymous",
          },
        },
      ],
      plugins: [
        starlightLinksValidator({
          failOnError: true,
          exclude: [
            // Exclude links to the generated OpenAPI custom pages where
            // hash anchors (#tag/...) cannot be validated.
            "/developers/api{,/,**/**}",
            "/scheduleonce/developers/api{,/,**/**}",
          ],
        }),
        starlightPageActions({
          actions: {
            chatgpt: true,
            claude: true,
            markdown: true,
          },
          share: false,
        }),
        starlightLlmsTxt({
          projectName: "OnceHub Help Center",
        }),
      ],
    }),
    openapiToMarkdown(),
  ],

  vite: {
    plugins: [tailwindcss()],
    server: {
      allowedHosts: [".trycloudflare.com"],
    },
  },
});
