// AUTO-GENERATED by scripts/migrate-ko.mjs
// Edit this file to control sidebar order, labels, and structure.
//  • Reorder groups  → move the blocks
//  • Rename a group  → change the 'label' string
//  • Add a group     → add a new block with the autogenerate directory path
//  • Article order within a group → edit sidebar.order in the article's frontmatter

/** OnceHub platform sidebar entries */
export const onceHubSidebar = [
  {
    label: "Getting Started",
    collapsed: true,
    items: [
      {
        label: "Introduction To OnceHub",
        collapsed: true,
        items: [
          {
            autogenerate: { directory: "getting-started/introduction-oncehub" },
          },
        ],
      },
    ],
  },
  {
    label: "Profile Management",
    collapsed: true,
    items: [
      { slug: "profile-management/account-access-and-password-recovery" },
      { slug: "profile-management/managing-your-profile-in-oncehub" },
      {
        label: "Availability",
        collapsed: true,
        items: [
          { autogenerate: { directory: "profile-management/availability" } },
        ],
      },
      { slug: "profile-management/booking-calendar-user-notifications" },
    ],
  },
  {
    label: "User Integrations",
    collapsed: true,
    items: [
      {
        label: "Basics Of User Integrations",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/basics-user-integrations",
            },
          },
        ],
      },
      {
        label: "Google Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/google-calendar-connection",
            },
          },
        ],
      },
      {
        label: "MS Office 365 Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/ms-office365-calendar-connection",
            },
          },
        ],
      },
      {
        label: "Exchange Outlook Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "user-integrations/exchange-outlook-calendar-connection",
            },
          },
        ],
      },
      {
        label: "iCloud Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/icloud-calendar-connection",
            },
          },
        ],
      },
      {
        label: "Browser Extension",
        collapsed: true,
        items: [
          {
            autogenerate: { directory: "user-integrations/browser-extension" },
          },
        ],
      },
      {
        label: "Security Best Practices",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/security-best-practices",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Account Administration",
    collapsed: true,
    items: [
      {
        label: "User Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/user-management",
            },
          },
        ],
      },
      {
        label: "User Attributes",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/user-attributes",
            },
          },
        ],
      },
      {
        label: "Objects and Properties",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/objects-properties",
            },
          },
        ],
      },
      {
        label: "Booking Calendar Templates",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/booking-calendar-templates",
            },
          },
        ],
      },
      {
        label: "Locations and Rooms",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/locations-rooms",
            },
          },
        ],
      },
      {
        label: "Account Permissions",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/account-permissions",
            },
          },
        ],
      },
    ],
  },
  {
    label: "AI Front Office Workers",
    collapsed: true,
    items: [
      {
        label: "Website Assistant",
        collapsed: true,
        items: [
          {
            label: "Chatbots",
            collapsed: true,
            items: [
              {
                label: "Introduction to Chatbots",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/introduction-to-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/creating-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-questions-to-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-messages-to-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/routing-your-interactions-in-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/legal-and-compliance",
                  },
                ],
              },
              {
                label: "Hand off to Human",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/getting-started-with-instant-calls-in-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/offering-instant-video-calls-with-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/offering-scheduling-in-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/offering-live-chat-with-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/monitoring-and-barging-into-live-chats",
                  },
                ],
              },
              {
                label: "Sharing and Embedding",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/sharing-your-chatbot-as-standalone-page",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/embedding-your-chatbots-on-your-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/sharing-files-in-live-chat",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-clickfunnels-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-godaddy-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-hubspot-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-leadpages-landing-page",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-squarespace-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-unbounce-landing-page",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-weebly-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-wix-website",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/adding-chatbots-to-your-wordpress-website",
                  },
                ],
              },
              {
                label: "Notifications",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/setting-up-user-notifications-for-your-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/enabling-google-chat-notifications-for-live-engagements-in-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/enabling-microsoft-teams-notifications-for-live-engagements-in-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/enabling-slack-notifications-for-live-engagements-in-chatbots",
                  },
                ],
              },
              {
                label: "Contact and Data Management",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/contacts-in-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/assigning-contacts-captured-through-chatbots-to-users",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/updating-status-of-contacts-captured-through-your-chatbot",
                  },
                ],
              },
              {
                label: "Automatically Reaching Out to Website Visitors",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/automatically-reach-out-to-your-website-visitors-with-chatbot",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/defining-audiences-for-your-website-visitors",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/targeting-an-audience-with-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/customizing-design-of-your-automatic-reach-out-bots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/installing-automatic-reach-out-on-your-website",
                  },
                ],
              },
              {
                label: "AI-Powered Chatbots",
                collapsed: true,
                items: [
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/engage-with-visitors-using-an-ai-conversation",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/generic-ai-instruction-template",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-business-consulting",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-coaching",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-education",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-finance",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-real-estate",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/ai-instruction-template-for-wellness",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/how-to-create-an-ai-agent",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/how-to-use-ai-agents-within-your-chatbots",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/defining-your-ai-agents-conversation-guidelines",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/how-to-manage-knowledge-sources-for-ai-agents",
                  },
                  {
                    slug: "ai-front-office-workers/website-assistant/chatbots/how-to-monitor-and-barge-into-ai-conversations",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Human Engagement",
    collapsed: true,
    items: [
      {
        label: "Booking Calendars",
        collapsed: true,
        items: [
          {
            label: "Introduction to Booking Calendars",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/introduction-to-booking-calendars",
                },
              },
            ],
          },
          {
            label: "Booking Settings",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/booking-settings",
                },
              },
            ],
          },
          {
            label: "Booking Forms",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/booking-forms",
                },
              },
            ],
          },
          {
            label: "Notifications",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/notifications",
                },
              },
            ],
          },
          {
            label: "Sharing and Embedding",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/sharing-embedding",
                },
              },
            ],
          },
          {
            label: "Phone Booking",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/phone-booking",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Booking Hubs",
        collapsed: true,
        items: [
          {
            label: "Introduction To Booking Hubs",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-hubs/introduction-to-booking-hubs",
                },
              },
            ],
          },
          {
            label: "Configuring Booking Hubs",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-hubs/configuring-bookng-hubs",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Routing Forms",
        collapsed: true,
        items: [
          {
            label: "Introduction To Routing Forms",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/introduction-to-routing-forms",
                },
              },
            ],
          },
          {
            label: "Contact and Data Management",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/contact-data-management",
                },
              },
            ],
          },
          {
            label: "Notifications",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/notifications",
                },
              },
            ],
          },
          {
            label: "Phone Screening",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/phone-screening",
                },
              },
            ],
          },
          {
            label: "Hand Off to Human",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/offering-scheduling",
                },
              },
            ],
          },
          {
            label: "Sharing and Embedding",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/sharing-embedding",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Activities Analytics",
    collapsed: true,
    items: [
      {
        label: "Activity Management",
        collapsed: true,
        items: [
          {
            label: "Meeting Management",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "activities-analytics/activity-management/meeting-management",
                },
              },
            ],
          },
          {
            slug: "activities-analytics/activity-management/managing-guest-activities",
          },
          {
            slug: "activities-analytics/activity-management/exporting-your-oncehub-activities",
          },
          {
            slug: "activities-analytics/activity-management/filtering-your-oncehub-activities",
          },
          {
            slug: "activities-analytics/activity-management/phone-booking-conversation-summary-and-recording",
          },
          {
            slug: "activities-analytics/activity-management/understanding-test-activity-behavior-in-chatbots-and-routing-forms",
          },
          { slug: "activities-analytics/activity-management/alert-center" },
        ],
      },
      {
        label: "Reporting Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "activities-analytics/reporting-analytics",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Contact Management",
    collapsed: true,
    items: [{ autogenerate: { directory: "contact-management" } }],
  },
  {
    label: "Account Integrations",
    collapsed: true,
    items: [
      {
        label: "Automation",
        collapsed: true,
        items: [
          {
            label: "API & Webhooks",
            collapsed: true,
            items: [
              {
                slug: "account-integrations/automation/api-and-webhooks/api-key-security-management",
              },
              {
                slug: "account-integrations/automation/api-and-webhooks/creating-and-managing-webhooks-via-oncehub",
              },
              {
                slug: "account-integrations/automation/api-and-webhooks/custom-booking-calendar-integrations-with-webhooks-and-apis",
              },
            ],
          },
          {
            label: "Zapier",
            collapsed: true,
            items: [
              {
                slug: "account-integrations/automation/zapier/integrating-oncehub-with-zapier",
              },
              {
                slug: "account-integrations/automation/zapier/automate-your-scheduling-workflow-by-using-zapier",
              },
              {
                slug: "account-integrations/automation/zapier/oncehub-triggers-and-actions-for-zapier",
              },
              {
                slug: "account-integrations/automation/zapier/setting-up-zap-for-booking-calendars-using-contact-properties",
              },
              {
                slug: "account-integrations/automation/zapier/setting-up-zap-for-booking-calendars-using-meeting-properties",
              },
              {
                slug: "account-integrations/automation/zapier/setting-up-zap-for-chatbots",
              },
              {
                slug: "account-integrations/automation/zapier/setting-up-zap-for-routing-forms",
              },
            ],
          },
          {
            label: "OnceHub MCP",
            collapsed: true,
            items: [
              {
                slug: "account-integrations/automation/oncehub-mcp/how-to-connect-oncehub-to-your-ai-assistant",
              },
              {
                slug: "account-integrations/automation/oncehub-mcp/list-of-supported-tools",
              },
              {
                slug: "account-integrations/automation/oncehub-mcp/manage-scheduling-with-ai-prompts",
              },
            ],
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-integrately",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-keragon",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-make",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-microsoft-copilot-studio",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-n8n",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-viasocket",
          },
        ],
      },
      {
        label: "CRM",
        collapsed: true,
        items: [
          { slug: "account-integrations/crm/integrating-with-your-crm" },
          {
            slug: "account-integrations/crm/integrating-oncehub-with-salesforce",
          },
          {
            slug: "account-integrations/crm/integrating-oncehub-with-your-salesforce-sandbox-environment",
          },
          { slug: "account-integrations/crm/integrating-oncehub-with-hubspot" },
          {
            slug: "account-integrations/crm/troubleshooting-crm-integration-issues",
          },
        ],
      },
      {
        label: "Corporate Mailbox",
        collapsed: true,
        items: [
          {
            slug: "account-integrations/corporate-mailbox/sending-scheduling-notifications-from-corporate-amazon-ses-account",
          },
          {
            slug: "account-integrations/corporate-mailbox/sending-scheduling-notifications-from-corporate-gmail-account",
          },
          {
            slug: "account-integrations/corporate-mailbox/sending-scheduling-notifications-from-corporate-office-365-account",
          },
          {
            slug: "account-integrations/corporate-mailbox/sending-scheduling-notifications-from-custom-corporate-smtp-server",
          },
        ],
      },
      {
        label: "Payment Collection",
        collapsed: true,
        items: [
          {
            label: "Stripe",
            collapsed: true,
            items: [
              {
                slug: "account-integrations/payment-collection/stripe/introduction-to-stripe-integration",
              },
              {
                slug: "account-integrations/payment-collection/stripe/how-to-connect-oncehub-with-stripe",
              },
              {
                slug: "account-integrations/payment-collection/stripe/how-to-configure-payment-collection-on-your-booking-calendar",
              },
              {
                slug: "account-integrations/payment-collection/stripe/how-payment-transaction-details-are-sent-to-your-guests",
              },
              {
                slug: "account-integrations/payment-collection/stripe/how-oncehub-handles-reassigned-rescheduled-and-canceled-paid-meetings",
              },
            ],
          },
        ],
      },
      {
        label: "Security And Compliance",
        collapsed: true,
        items: [
          {
            slug: "account-integrations/security-and-compliance/how-to-integrate-oncehub-with-microsoft-entra-id",
          },
          {
            slug: "user-account-management/account-management/single-sign-on-sso/integrating-oncehub-with-microsoft-entra-id-to-allow-for-sso",
          },
          {
            slug: "account-integrations/security-and-compliance/how-to-add-and-delete-oncehub-users-with-microsoft-entra-id",
          },
          {
            slug: "user-account-management/account-management/single-sign-on-sso/integrating-oncehub-with-okta-to-allow-for-sso",
          },
          {
            slug: "user-account-management/account-management/single-sign-on-sso/integrating-oncehub-with-onelogin-to-allow-for-sso",
          },
        ],
      },
      {
        label: "Analytics",
        collapsed: true,
        items: [
          {
            slug: "account-integrations/analytics/connect-oncehub-to-your-google-tag-manager",
          },
          {
            slug: "account-integrations/analytics/tracking-oncehub-events-in-google-tag-manager",
          },
        ],
      },
    ],
  },
  {
    label: "Billing",
    collapsed: true,
    items: [
      { slug: "billing/managing-your-subscription" },
      { slug: "billing/managing-seats-in-oncehub" },
      { slug: "billing/managing-phone-numbers" },
      { slug: "billing/managing-payment-methods" },
      { slug: "billing/sms-credits-in-oncehub" },
      {
        slug: "billing/sms-delivery-statuses-troubleshooting-and-regional-guidelines",
      },
      { slug: "billing/accessing-and-exporting-your-centralized-sms-logs" },
      { slug: "billing/canceling-your-subscription" },
      { slug: "billing/deleting-your-account" },
    ],
  },
  {
    label: "Security & Compliance",
    collapsed: true,
    items: [
      {
        label: "Security",
        collapsed: true,
        items: [
          { slug: "security-compliance/security/introduction-to-security" },
          { slug: "security-compliance/security/security-settings" },
          { slug: "security-compliance/security/security-best-practices" },
          {
            slug: "security-compliance/security/configuring-single-sign-on-sso-for-your-account",
          },
          {
            slug: "security-compliance/security/storing-and-protecting-your-sign-in-credentials",
          },
          {
            slug: "security-compliance/security/how-to-prevent-automated-and-manual-spam-bookings",
          },
          { slug: "security-compliance/security/account-lockout-policies" },
          { slug: "security-compliance/security/password-policies" },
          { slug: "security-compliance/security/session-policies" },
        ],
      },
      {
        label: "Privacy",
        collapsed: true,
        items: [
          { slug: "security-compliance/privacy/oncehub-cookies" },
          {
            slug: "security-compliance/privacy/data-protection-officer-and-eu-representative",
          },
          {
            slug: "security-compliance/privacy/establishing-lawful-basis-for-processing-under-gdpr",
          },
          { slug: "security-compliance/privacy/gdpr-compliance" },
          { slug: "security-compliance/privacy/gdpr-data-deletion-request" },
          { slug: "security-compliance/privacy/gdpr-terminology" },
          {
            slug: "security-compliance/privacy/maintaining-records-of-processing-under-gdpr",
          },
          {
            slug: "security-compliance/privacy/securing-your-account-according-to-gdpr",
          },
          { slug: "security-compliance/privacy/faqs-about-gdpr" },
          { slug: "security-compliance/privacy/gdprs-privacy-principles" },
        ],
      },
      {
        label: "Compliance",
        collapsed: true,
        items: [
          { slug: "security-compliance/compliance/compliance-at-oncehub" },
          {
            slug: "security-compliance/compliance/setting-up-compliance-bcc-email",
          },
          { slug: "security-compliance/compliance/what-is-hipaa" },
          { slug: "security-compliance/compliance/oncehub-baa" },
          { slug: "security-compliance/compliance/hipaa-compliance" },
        ],
      },
    ],
  },
  {
    label: "What's New",
    collapsed: true,
    items: [{ autogenerate: { directory: "whats-new" } }],
  },
];

/** ScheduleOnce Classic sidebar entries */
export const scheduleOnceSidebar = [
  {
    label: "User Integrations",
    collapsed: true,
    items: [
      {
        label: "Basics User Integrations",
        collapsed: true,
        items: [
          {
            slug: "scheduleonce/user-integrations/basics-user-integrations/how-busy-time-from-your-connected-calendar-is-used-to-manage-availability",
          },
          {
            slug: "scheduleonce/user-integrations/basics-user-integrations/what-you-need-to-know-before-disconnecting-your-calendar",
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/user-integrations/basics-user-integrations/troubleshooting",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Google Calendar Connection",
        collapsed: true,
        items: [
          {
            slug: "scheduleonce/user-integrations/google-calendar-connection/managing-your-oncehub-integration-with-google-workspace",
          },
          {
            slug: "scheduleonce/user-integrations/google-calendar-connection/how-to-workaround-google-calendar-quota",
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/user-integrations/google-calendar-connection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Exchange Outlook Calendar Connection",
        collapsed: true,
        items: [
          {
            slug: "scheduleonce/user-integrations/exchange-outlook-calendar-connection/managing-your-oncehub-integration-with-microsoft-exchange-calendar",
          },
          {
            slug: "scheduleonce/user-integrations/exchange-outlook-calendar-connection/outlook-calendar-events-not-showing-in-expected-time-zone",
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/user-integrations/exchange-outlook-calendar-connection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
      {
        label: "iCloud Calendar Connection",
        collapsed: true,
        items: [
          {
            slug: "scheduleonce/user-integrations/icloud-calendar-connection/managing-your-oncehub-integration-with-icloud-calendar",
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/user-integrations/icloud-calendar-connection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
      {
        label: "MS Office 365 Calendar Connection",
        collapsed: true,
        items: [
          {
            slug: "scheduleonce/user-integrations/ms-office365-calendar-connection/managing-your-oncehub-integration-with-microsoft-office-365",
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/user-integrations/ms-office365-calendar-connection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Account Integrations",
    collapsed: true,
    items: [
      {
        label: "Automation",
        collapsed: true,
        items: [
          {
            label: "API",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "scheduleonce/account-integrations/api",
                },
              },
            ],
          },
          {
            label: "Zapier",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/automation/zapier",
                },
              },
            ],
          },
          {
            label: "viaSocket",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/automation/viaSocket",
                },
              },
            ],
          },
        ],
      },
      {
        label: "CRM",
        collapsed: true,
        items: [
          {
            label: "Salesforce",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "scheduleonce/account-integrations/crm/salesforce",
                },
              },
            ],
          },
          {
            label: "Infusionsoft",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/crm/infusionsoft",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Payment Collection",
        collapsed: true,
        items: [
          {
            label: "Paypal",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/payment-collection/paypal",
                },
              },
            ],
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/payment-collection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Introduction to Booking Pages",
    collapsed: true,
    items: [
      {
        autogenerate: {
          directory: "scheduleonce/introduction-to-booking-pages",
        },
      },
    ],
  },
  {
    label: "Event Types & Booking Pages",
    collapsed: true,
    items: [
      {
        label: "User Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/user-notifications",
            },
          },
        ],
      },
      {
        label: "Booking Pages",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/booking-pages",
            },
          },
        ],
      },
      {
        label: "Scheduling Options",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/scheduling-options",
            },
          },
        ],
      },
      {
        label: "Booking Forms & Redirect",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/booking-forms-redirect",
            },
          },
        ],
      },
      {
        label: "Event Types",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/event-types",
            },
          },
        ],
      },
      {
        label: "Categories",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/categories",
            },
          },
        ],
      },
      {
        label: "Customer Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/customer-notifications",
            },
          },
        ],
      },
      {
        label: "Timeslot Settings",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/timeslot-settings",
            },
          },
        ],
      },
      {
        label: "Sms Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/sms-notifications",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Master Pages & Resource Pools",
    collapsed: true,
    items: [
      {
        label: "Resource Pools",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/resource-pools",
            },
          },
        ],
      },
      {
        label: "Panel Meetings",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/panel-meetings",
            },
          },
        ],
      },
      {
        label: "Master Pages",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/master-pages",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Customization & Branding",
    collapsed: true,
    items: [
      {
        label: "Theme Designer",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/customization-branding/theme-designer",
            },
          },
        ],
      },
      {
        label: "Localization Customer Text",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/localization-customer-text",
            },
          },
        ],
      },
      {
        label: "Notification Templates Editor",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/notification-templates-editor",
            },
          },
        ],
      },
      {
        label: "Booking Forms Editor",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/booking-forms-editor",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Sharing & Publishing",
    collapsed: true,
    items: [
      {
        label: "General & One-time Links",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/sharing-publishing/general-one-time-links",
            },
          },
        ],
      },
      {
        label: "Personalized Links",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/sharing-publishing/personalized-links",
            },
          },
        ],
      },
      {
        label: "Publishing on Websites",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/sharing-publishing/publishing-on-websites",
            },
          },
        ],
      },
      {
        label: "Web Form Integration",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/sharing-publishing/web-form-integration",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Managing Bookings",
    collapsed: true,
    items: [
      {
        label: "Responding to Booking Requests",
        collapsed: true,
        items: [
          {
            label: "Responding to Booking Requests",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/managing-bookings/responding-to-booking-requests/responding-to-booking-requests",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Cancel or Reschedule",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/cancel-reschedule",
            },
          },
        ],
      },
      {
        label: "Reassign",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/reassign",
            },
          },
        ],
      },
      {
        label: "Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/analytics",
            },
          },
        ],
      },
      {
        label: "Troubleshooting",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/troubleshooting",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Reporting",
    collapsed: true,
    items: [{ autogenerate: { directory: "scheduleonce/reporting" } }],
  },
  {
    label: "Recommended Configuration",
    collapsed: true,
    items: [
      {
        label: "Single User Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/single-user-scenarios",
            },
          },
        ],
      },
      {
        label: "Multi User Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/multi-user-scenarios",
            },
          },
        ],
      },
      {
        label: "Multiple Attendee Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/multiple-attendee-scenarios",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Insights & Operations",
    collapsed: true,
    items: [
      {
        label: "Profile Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/profile-management",
            },
          },
        ],
      },
      {
        label: "User Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/user-management",
            },
          },
        ],
      },
      {
        label: "Billing & Subscription Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/insights-operations/billing-subscription-management",
            },
          },
        ],
      },
      {
        label: "Reporting & Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/reporting-analytics",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Security & Compliance",
    collapsed: true,
    items: [
      {
        label: "Privacy",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/security-compliance/privacy",
            },
          },
        ],
      },
    ],
  },
];
