// AUTO-GENERATED by scripts/migrate-ko.mjs
// Edit this file to control sidebar order, labels, and structure.
//  • Reorder groups  → move the blocks
//  • Rename a group  → change the 'label' string
//  • Add a group     → add a new block with the autogenerate directory path
//  • Article order within a group → edit sidebar.order in the article's frontmatter

/** OnceHub platform sidebar entries */
export const onceHubSidebar = [
  {
    label: "Getting Started",
    collapsed: true,
    items: [
      {
        label: "Introduction To OnceHub",
        collapsed: true,
        items: [
          {
            autogenerate: { directory: "getting-started/introduction-oncehub" },
          },
        ],
      },
    ],
  },
  {
    label: "Profile Management",
    collapsed: true,
    items: [
      { slug: "profile-management/account-access-and-password-recovery" },
      { slug: "profile-management/managing-your-profile-in-oncehub" },
      {
        label: "Availability",
        collapsed: true,
        items: [
          { autogenerate: { directory: "profile-management/availability" } },
        ],
      },
      { slug: "profile-management/booking-calendar-user-notifications" },
    ],
  },
  {
    label: "User Integrations",
    collapsed: true,
    items: [
      {
        label: "Basics Of User Integrations",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/basics-user-integrations",
            },
          },
        ],
      },
      {
        label: "Google Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/google-calendar-connection",
            },
          },
        ],
      },
      {
        label: "MS Office 365 Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/ms-office365-calendar-connection",
            },
          },
        ],
      },
      {
        label: "Exchange Outlook Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "user-integrations/exchange-outlook-calendar-connection",
            },
          },
        ],
      },
      {
        label: "iCloud Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/icloud-calendar-connection",
            },
          },
        ],
      },
      {
        label: "Browser Extension",
        collapsed: true,
        items: [
          {
            autogenerate: { directory: "user-integrations/browser-extension" },
          },
        ],
      },
      {
        label: "Security Best Practices",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "user-integrations/security-best-practices",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Account Administration",
    collapsed: true,
    items: [
      {
        label: "User Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/user-management",
            },
          },
        ],
      },
      {
        label: "User Attributes",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/user-attributes",
            },
          },
        ],
      },
      {
        label: "Objects and Properties",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/objects-properties",
            },
          },
        ],
      },
      {
        label: "Booking Calendar Templates",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/booking-calendar-templates",
            },
          },
        ],
      },
      {
        label: "Locations and Rooms",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/locations-rooms",
            },
          },
        ],
      },
      {
        label: "Account Permissions",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-administration/account-permissions",
            },
          },
        ],
      },
    ],
  },
  {
    label: "AI Front Office Workers",
    collapsed: true,
    items: [
      {
        label: "Website Assistant",
        collapsed: true,
        items: [
          {
            label: "Chatbots",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "ai-front-office-workers/website-assistant/chatbots",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Human Engagement",
    collapsed: true,
    items: [
      {
        label: "Booking Calendars",
        collapsed: true,
        items: [
          {
            label: "Booking Settings",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/booking-settings",
                },
              },
            ],
          },
          {
            label: "Availability",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/availability",
                },
              },
            ],
          },
          {
            label: "Booking Forms",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/booking-forms",
                },
              },
            ],
          },
          {
            label: "Notifications",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/notifications",
                },
              },
            ],
          },
          {
            label: "Templates",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/templates",
                },
              },
            ],
          },
          {
            label: "Introduction To Booking Calendars",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/introduction-to-booking-calendars",
                },
              },
            ],
          },
          {
            label: "Sharing Embedding",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-calendars/sharing-embedding",
                },
              },
            ],
          },
          {
            label: "Phone Booking",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/booking-calendars/phone-booking",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Routing Forms",
        collapsed: true,
        items: [
          {
            label: "Introduction To Routing Forms",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/introduction-to-routing-forms",
                },
              },
            ],
          },
          {
            label: "Sharing Embedding",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/sharing-embedding",
                },
              },
            ],
          },
          {
            label: "Contact Data Management",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/contact-data-management",
                },
              },
            ],
          },
          {
            label: "Phone Screening",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/phone-screening",
                },
              },
            ],
          },
          {
            label: "Offering Scheduling",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/offering-scheduling",
                },
              },
            ],
          },
          {
            label: "Configuring Your Routing Form",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/routing-forms/configuring-your-routing-form",
                },
              },
            ],
          },
          {
            label: "Notifications",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "human-engagement/routing-forms/notifications",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Booking Hubs",
        collapsed: true,
        items: [
          {
            label: "Configuring Booking Hubs",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-hubs/configuring-bookng-hubs",
                },
              },
            ],
          },
          {
            label: "Introduction To Booking Hubs",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "human-engagement/booking-hubs/introduction-to-booking-hubs",
                },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "Activities Analytics",
    collapsed: true,
    items: [
      {
        label: "Activity Management",
        collapsed: true,
        items: [
          { slug: "activities-analytics/activity-management/alert-center" },
          {
            slug: "activities-analytics/activity-management/exporting-your-oncehub-activities",
          },
          {
            slug: "activities-analytics/activity-management/filtering-your-oncehub-activities",
          },
          {
            slug: "activities-analytics/activity-management/managing-guest-activities",
          },
          {
            slug: "activities-analytics/activity-management/phone-booking-conversation-summary-and-recording",
          },
          {
            slug: "activities-analytics/activity-management/understanding-test-activity-behavior-in-chatbots-and-routing-forms",
          },
          {
            label: "Meeting Management",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "activities-analytics/activity-management/meeting-management",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Reporting Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "activities-analytics/reporting-analytics",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Contact Management",
    collapsed: true,
    items: [{ autogenerate: { directory: "contact-management" } }],
  },
  {
    label: "Account Integrations",
    collapsed: true,
    items: [
      {
        label: "Analytics",
        collapsed: true,
        items: [
          { autogenerate: { directory: "account-integrations/analytics" } },
        ],
      },
      {
        label: "Automation",
        collapsed: true,
        items: [
          {
            slug: "account-integrations/automation/api-key-security-management",
          },
          {
            slug: "account-integrations/automation/creating-and-managing-webhooks-via-oncehub",
          },
          {
            slug: "account-integrations/automation/custom-booking-calendar-integrations-with-webhooks-and-apis",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-integrately",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-keragon",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-make",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-microsoft-copilot-studio",
          },
          {
            slug: "account-integrations/automation/integrating-oncehub-with-viasocket",
          },
          {
            label: "Zapier",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "account-integrations/automation/zapier",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Corporate Mailbox",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-integrations/corporate-mailbox",
            },
          },
        ],
      },
      {
        label: "CRM",
        collapsed: true,
        items: [{ autogenerate: { directory: "account-integrations/crm" } }],
      },
      {
        label: "Payment Collection",
        collapsed: true,
        items: [
          {
            label: "Stripe",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "account-integrations/payment-collection/stripe",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Security And Compliance",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "account-integrations/security-and-compliance",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Billing",
    collapsed: true,
    items: [{ autogenerate: { directory: "billing" } }],
  },
  {
    label: "Security & Compliance",
    collapsed: true,
    items: [
      {
        label: "Security",
        collapsed: true,
        items: [
          { autogenerate: { directory: "security-compliance/security" } },
        ],
      },
      {
        label: "Compliance",
        collapsed: true,
        items: [
          { autogenerate: { directory: "security-compliance/compliance" } },
        ],
      },
      {
        label: "Privacy",
        collapsed: true,
        items: [{ autogenerate: { directory: "security-compliance/privacy" } }],
      },
    ],
  },
  {
    label: "What's New",
    collapsed: true,
    items: [{ autogenerate: { directory: "whats-new" } }],
  },
];

/** ScheduleOnce Classic sidebar entries */
export const scheduleOnceSidebar = [
  {
    label: "Insights & Operations",
    collapsed: true,
    items: [
      {
        label: "Billing & Subscription Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/insights-operations/billing-subscription-management",
            },
          },
        ],
      },
      {
        label: "Profile Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/profile-management",
            },
          },
        ],
      },
      {
        label: "Reporting Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/reporting-analytics",
            },
          },
        ],
      },
      {
        label: "User Management",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/insights-operations/user-management",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Event Types & Booking Pages",
    collapsed: true,
    items: [
      {
        label: "User Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/user-notifications",
            },
          },
        ],
      },
      {
        label: "Booking Pages",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/booking-pages",
            },
          },
        ],
      },
      {
        label: "Scheduling Options",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/scheduling-options",
            },
          },
        ],
      },
      {
        label: "Booking Forms & Redirect",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/booking-forms-redirect",
            },
          },
        ],
      },
      {
        label: "Event Types",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/event-types",
            },
          },
        ],
      },
      {
        label: "Categories",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/event-types-booking-pages/categories",
            },
          },
        ],
      },
      {
        label: "Customer Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/customer-notifications",
            },
          },
        ],
      },
      {
        label: "Timeslot Settings",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/timeslot-settings",
            },
          },
        ],
      },
      {
        label: "Sms Notifications",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/event-types-booking-pages/sms-notifications",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Recommended Configuration",
    collapsed: true,
    items: [
      {
        label: "Single User Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/single-user-scenarios",
            },
          },
        ],
      },
      {
        label: "Multi User Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/multi-user-scenarios",
            },
          },
        ],
      },
      {
        label: "Multiple Attendee Scenarios",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/recommended-configuration/multiple-attendee-scenarios",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Reporting",
    collapsed: true,
    items: [{ autogenerate: { directory: "scheduleonce/reporting" } }],
  },
  {
    label: "Sharing & Publishing",
    collapsed: true,
    items: [
      {
        label: "Publishing On Websites",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/sharing-publishing/publishing-on-websites",
            },
          },
        ],
      },
      {
        label: "General One Time Links",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/sharing-publishing/general-one-time-links",
            },
          },
        ],
      },
      {
        label: "Personalized Links",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/sharing-publishing/personalized-links",
            },
          },
        ],
      },
      {
        label: "Web Form Integration",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/sharing-publishing/web-form-integration",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Account Integrations",
    collapsed: true,
    items: [
      {
        label: "CRM",
        collapsed: true,
        items: [
          {
            label: "Salesforce",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory: "scheduleonce/account-integrations/crm/salesforce",
                },
              },
            ],
          },
          {
            label: "Infusionsoft",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/crm/infusionsoft",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Payment Collection",
        collapsed: true,
        items: [
          {
            label: "Paypal",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/payment-collection/paypal",
                },
              },
            ],
          },
          {
            label: "Troubleshooting",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/payment-collection/troubleshooting",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Automation",
        collapsed: true,
        items: [
          {
            label: "Zapier",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/automation/zapier",
                },
              },
            ],
          },
          {
            label: "viaSocket",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/account-integrations/automation/viaSocket",
                },
              },
            ],
          },
        ],
      },
      {
        label: "API",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/account-integrations/API",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Master Pages & Resource Pools",
    collapsed: true,
    items: [
      {
        label: "Resource Pools",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/resource-pools",
            },
          },
        ],
      },
      {
        label: "Panel Meetings",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/panel-meetings",
            },
          },
        ],
      },
      {
        label: "Master Pages",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/master-pages-resource-pools/master-pages",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Customization & Branding",
    collapsed: true,
    items: [
      {
        label: "Theme Designer",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/customization-branding/theme-designer",
            },
          },
        ],
      },
      {
        label: "Localization Customer Text",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/localization-customer-text",
            },
          },
        ],
      },
      {
        label: "Notification Templates Editor",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/notification-templates-editor",
            },
          },
        ],
      },
      {
        label: "Booking Forms Editor",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/customization-branding/booking-forms-editor",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Managing Bookings",
    collapsed: true,
    items: [
      {
        label: "Responding To Booking Requests",
        collapsed: true,
        items: [
          {
            label: "Responding To Booking Requests",
            collapsed: true,
            items: [
              {
                autogenerate: {
                  directory:
                    "scheduleonce/managing-bookings/responding-to-booking-requests/responding-to-booking-requests",
                },
              },
            ],
          },
        ],
      },
      {
        label: "Reassign",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/reassign",
            },
          },
        ],
      },
      {
        label: "Cancel Reschedule",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/cancel-reschedule",
            },
          },
        ],
      },
      {
        label: "Troubleshooting",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/troubleshooting",
            },
          },
        ],
      },
      {
        label: "Analytics",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/managing-bookings/analytics",
            },
          },
        ],
      },
    ],
  },
  {
    label: "User Integrations",
    collapsed: true,
    items: [
      {
        label: "Basics User Integrations",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/user-integrations/basics-user-integrations",
            },
          },
        ],
      },
      {
        label: "Google Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/user-integrations/google-calendar-connection",
            },
          },
        ],
      },
      {
        label: "Exchange Outlook Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/user-integrations/exchange-outlook-calendar-connection",
            },
          },
        ],
      },
      {
        label: "iCloud Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/user-integrations/icloud-calendar-connection",
            },
          },
        ],
      },
      {
        label: "MS Office 365 Calendar Connection",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory:
                "scheduleonce/user-integrations/ms-office365-calendar-connection",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Security & Compliance",
    collapsed: true,
    items: [
      {
        label: "Privacy",
        collapsed: true,
        items: [
          {
            autogenerate: {
              directory: "scheduleonce/security-compliance/privacy",
            },
          },
        ],
      },
    ],
  },
  {
    label: "Introduction to Booking Pages",
    collapsed: true,
    items: [
      {
        autogenerate: {
          directory: "scheduleonce/introduction-to-booking-pages",
        },
      },
    ],
  },
];
